### PR TITLE
Include author, if possible,  when migrating to content bank

### PR DESCRIPTION
**Pull request by sarjona**
Content in the content bank will be migrated taking the user who created the mod_hvp as author (when this information exists in logs).

### CODE REVIEW

**Review by doctorlard — COMMENTED** [review]
Could the author information come from mdl_files instead, or in the case where it's not found in the logs?

**Comment by sarjona** [comment]
@doctorlard The mod_hvp stores the H5P content in database so there is no .h5p file in mdl_files... That's why the only approach we can use here (or, at least, the only one I was able to find), is trying to find the author in the logs :-(

**Comment by doctorlard** [comment]
I'm working on something that can try and get the user id from files, or fall back to the first user with `moodle/contentbank:manageowncontent` or `moodle/contentbank:manageanycontent` - which should be an editingteacher or manager/coursecreator respectively.

**Comment by sarjona** [comment]
I'm closing this because a new PR with more cases has been sent: https://github.com/moodlehq/moodle-tool_migratehvp2h5p/pull/46

**Pull request closed without merging**
